version: '3.8'

services:
  db:
    image: postgres:15.0
    container_name: my_chat_db
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - messaging-network

  app:
    build: .
    container_name: my_chat_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - messaging-network

volumes:
  db-data:

networks:
  messaging-network:
    driver: bridge