version: '3.8'

services:
  db:
    image: postgres:15.0
    container_name: my_chat_db
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - messaging-network

  app:
    build: .
    container_name: my_chat_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - messaging-network

  redis:
    image: redis:alpine
    container_name: my_chat_redis
    ports:
      - "6379:6379"
    networks:
      - messaging-network

  celery:
    build: .
    container_name: my_chat_celery
    command: celery -A app.celery.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - messaging-network

  nginx:
    image: nginx:latest
    container_name: my_chat_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/app/static
    depends_on:
      - app
    networks:
      - messaging-network

volumes:
  db-data:

networks:
  messaging-network:
    driver: bridge
