"""sent notify for user

Revision ID: 0137f9fcb5b8
Revises: 5a6e75e2607a
Create Date: 2024-10-22 08:16:17.814787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0137f9fcb5b8'
down_revision: Union[str, None] = '5a6e75e2607a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_sent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_sent')
    # ### end Alembic commands ###
