"""Create telegram_users table

Revision ID: 4afa5c6cfff5
Revises: 4e5db0c934ee
Create Date: 2024-10-21 09:06:34.809435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afa5c6cfff5'
down_revision: Union[str, None] = '4e5db0c934ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
